# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b185d644074e239b529591e02911e9fc340b3c60a2d8c7798a59cc121024af8699b906bedf8131a7f8c5591d697a37aecd47ae1053cbf7b0e7222d9b76ce9bf

test:
  secret_key_base: 685d1f99968cd99b2faad719fc14cc655158b6ccc0413f46f508fd52825338966227093ca104cb96262270e1fe5a99ac6edbb7c876a4b28f6cc29e5d7b471a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
